In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [7]:
df=pd.read_csv(r"C:\Users\Ravishankar Kumar\Desktop\heart_data - heart_data.csv")

In [8]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

### Data Seperation

In [9]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [10]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [13]:
df.drop("HeartDisease", axis = 1)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [14]:
x=df.drop("HeartDisease", axis = 1)

In [15]:
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [16]:
y=df["HeartDisease"]

In [17]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

### Data Splitting

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.20)

In [20]:
x.shape

(918, 11)

In [21]:
x_train.shape

(734, 11)

In [22]:
x_test.shape

(184, 11)

In [23]:
y_train.shape

(734,)

In [24]:
y_test.shape

(184,)

### Encoding - One Hot Encoder

In [34]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in d:\anaconda\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda\lib\site-packages (from scikit-learn) (3.5.0)

In [74]:
dfhouse=pd.read_csv(r"C:\Users\Ravishankar Kumar\Desktop\township.csv")

In [75]:
dfhouse

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [80]:
dfhouse.columns

Index(['town', 'area', 'price'], dtype='object')

In [77]:
dfhouse.shape

(13, 3)

In [78]:
dfhouse.dtypes

town     object
area      int64
price     int64
dtype: object

In [82]:
dfhouse["town"]

0     monroe township
1     monroe township
2     monroe township
3     monroe township
4     monroe township
5        west windsor
6        west windsor
7        west windsor
8        west windsor
9         robinsville
10        robinsville
11        robinsville
12        robinsville
Name: town, dtype: object

In [86]:
dfhouse["town"].unique()

array(['monroe township', 'west windsor', 'robinsville'], dtype=object)

In [87]:
from sklearn.preprocessing import OneHotEncoder

In [88]:
ohe=OneHotEncoder()

In [89]:
ohe

OneHotEncoder()

In [91]:
ohe.fit(dfhouse[["town"]])

OneHotEncoder()

In [92]:
ohe.transform(dfhouse[["town"]])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13 stored elements and shape (13, 3)>

In [93]:
ohe.transform(dfhouse[["town"]]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [101]:
ary=ohe.transform(dfhouse[["town"]]).toarray()

In [102]:
ary

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [103]:
ohe.categories_

[array(['monroe township', 'robinsville', 'west windsor'], dtype=object)]

In [104]:
dfhouse

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [97]:
ary.shape

(13, 3)

In [98]:
ary

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [99]:
pd.DataFrame(ary)

      0    1    2
0   1.0  0.0  0.0
1   1.0  0.0  0.0
2   1.0  0.0  0.0
3   1.0  0.0  0.0
4   1.0  0.0  0.0
5   0.0  0.0  1.0
6   0.0  0.0  1.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  1.0  0.0
11  0.0  1.0  0.0
12  0.0  1.0  0.0

In [105]:
columns = ohe.get_feature_names_out()

df_encoded = pd.DataFrame(
    ary,
    columns=columns
)

df_encoded.head()

   town_monroe township  town_robinsville  town_west windsor
0                   1.0               0.0                0.0
1                   1.0               0.0                0.0
2                   1.0               0.0                0.0
3                   1.0               0.0                0.0
4                   1.0               0.0                0.0

In [107]:
pd.DataFrame(ary, columns = ['monroe township', 'robinsville', 'west windsor'],dtype = "int")

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [110]:
dfend=pd.DataFrame(ary, columns = ['town_monroe township', 'town_robinsville', 'town_west windsor'],dtype = "int")

In [111]:
dfend

    town_monroe township  town_robinsville  town_west windsor
0                      1                 0                  0
1                      1                 0                  0
2                      1                 0                  0
3                      1                 0                  0
4                      1                 0                  0
5                      0                 0                  1
6                      0                 0                  1
7                      0                 0                  1
8                      0                 0                  1
9                      0                 1                  0
10                     0                 1                  0
11                     0                 1                  0
12                     0                 1                  0

In [112]:
dfend

    town_monroe township  town_robinsville  town_west windsor
0                      1                 0                  0
1                      1                 0                  0
2                      1                 0                  0
3                      1                 0                  0
4                      1                 0                  0
5                      0                 0                  1
6                      0                 0                  1
7                      0                 0                  1
8                      0                 0                  1
9                      0                 1                  0
10                     0                 1                  0
11                     0                 1                  0
12                     0                 1                  0

In [113]:
pd.concat([dfhouse,dfend], axis = 1)

,town,area,price,town_monroe township,town_robinsville,town_west windsor
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,565000,1,0,0
2,monroe township,3200,610000,1,0,0
3,monroe township,3600,680000,1,0,0
4,monroe township,4000,725000,1,0,0
5,west windsor,2600,585000,0,0,1
6,west windsor,2800,615000,0,0,1
7,west windsor,3300,650000,0,0,1
8,west windsor,3600,710000,0,0,1
9,robinsville,2600,575000,0,1,0
10,robinsville,2900,600000,0,1,0
11,robinsville,3100,620000,0,1,0
12,robinsville,3600,695000,0,1,0

In [114]:
dfhouse=pd.concat([dfhouse,dfend], axis = 1)

In [115]:
dfhouse

,town,area,price,town_monroe township,town_robinsville,town_west windsor
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,565000,1,0,0
2,monroe township,3200,610000,1,0,0
3,monroe township,3600,680000,1,0,0
4,monroe township,4000,725000,1,0,0
5,west windsor,2600,585000,0,0,1
6,west windsor,2800,615000,0,0,1
7,west windsor,3300,650000,0,0,1
8,west windsor,3600,710000,0,0,1
9,robinsville,2600,575000,0,1,0
10,robinsville,2900,600000,0,1,0
11,robinsville,3100,620000,0,1,0
12,robinsville,3600,695000,0,1,0

In [116]:
dfhouse.drop("town",axis = 1, inplace = True)

In [117]:
dfhouse

    area   price  town_monroe township  town_robinsville  town_west windsor
0   2600  550000                     1                 0                  0
1   3000  565000                     1                 0                  0
2   3200  610000                     1                 0                  0
3   3600  680000                     1                 0                  0
4   4000  725000                     1                 0                  0
5   2600  585000                     0                 0                  1
6   2800  615000                     0                 0                  1
7   3300  650000                     0                 0                  1
8   3600  710000                     0                 0                  1
9   2600  575000                     0                 1                  0
10  2900  600000                     0                 1                  0
11  3100  620000                     0                 1                  0
12  3600  695000                     0                 1                  0

### Data Seperation

In [118]:
dfhouse

    area   price  town_monroe township  town_robinsville  town_west windsor
0   2600  550000                     1                 0                  0
1   3000  565000                     1                 0                  0
2   3200  610000                     1                 0                  0
3   3600  680000                     1                 0                  0
4   4000  725000                     1                 0                  0
5   2600  585000                     0                 0                  1
6   2800  615000                     0                 0                  1
7   3300  650000                     0                 0                  1
8   3600  710000                     0                 0                  1
9   2600  575000                     0                 1                  0
10  2900  600000                     0                 1                  0
11  3100  620000                     0                 1                  0
12  3600  695000                     0                 1                  0

In [119]:
x = dfhouse.drop("price", axis = 1)

In [120]:
x

    area  town_monroe township  town_robinsville  town_west windsor
0   2600                     1                 0                  0
1   3000                     1                 0                  0
2   3200                     1                 0                  0
3   3600                     1                 0                  0
4   4000                     1                 0                  0
5   2600                     0                 0                  1
6   2800                     0                 0                  1
7   3300                     0                 0                  1
8   3600                     0                 0                  1
9   2600                     0                 1                  0
10  2900                     0                 1                  0
11  3100                     0                 1                  0
12  3600                     0                 1                  0

In [121]:
y = dfhouse["price"]

In [122]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64